wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1665465855.202189
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.8
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
